# Generated by Django 4.2 on 2023-04-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='agency name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('web', models.URLField(blank=True, verbose_name='web')),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='commission')),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
                'ordering': ['name'],
            },
        ),
    ]
