# Generated by Django 4.1.9 on 2023-05-23 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(help_text='Maximum 150 characters and minimum 1 character', max_length=150, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(help_text='Maximum 150 characters and minimum 1 character', max_length=150, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account',
            field=models.CharField(blank=True, help_text='IBAN should have between 15 and 34 characters', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(34)], verbose_name='bank account'),
        ),
    ]
