# Generated by Django 4.1.9 on 2023-05-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf1', models.FileField(upload_to='pdf1')),
                ('pdf2', models.FileField(upload_to='pdf2')),
            ],
        ),
    ]
