# Generated by Django 4.0.3 on 2022-05-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categorias',
            new_name='categoria',
        ),
    ]
