# Generated by Django 4.1.7 on 2023-04-07 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='practice area name')),
                ('init_date', models.DateField(verbose_name='init date')),
                ('end_date', models.DateField(verbose_name='end date')),
            ],
            options={
                'verbose_name': 'Practice',
                'verbose_name_plural': 'Practices',
                'ordering': ['init_date'],
            },
        ),
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='practice area name')),
            ],
            options={
                'verbose_name': 'Practice Area',
                'verbose_name_plural': 'Practice Areas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PracticeStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practices.practice', verbose_name='practice')),
            ],
        ),
    ]
