# Generated by Django 4.2 on 2023-04-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practices', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicestudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='student'),
        ),
        migrations.AddField(
            model_name='practice',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practices.practicearea', verbose_name='practice area'),
        ),
        migrations.AddField(
            model_name='practice',
            name='students',
            field=models.ManyToManyField(blank=True, through='practices.PracticeStudent', to='user.student', verbose_name='students'),
        ),
        migrations.AlterUniqueTogether(
            name='practicestudent',
            unique_together={('practice', 'student')},
        ),
    ]
