version: '3'

services:
  nginx:
    build: nginx
    ports:
      - "8070:80"
      - "8071:443"
    volumes:
      - ./src/static:/app/static
      - ./logs/nginx:/var/log/nginx
      - ./certs:/etc/nginx/ssl:ro
    depends_on:
      - django_admin_school
    restart: unless-stopped
    networks:
      - django_admin_school_net

  django_admin_school:
    build: .
    container_name: django_admin_school
    volumes:
      - ./logs:/var/log/app
      - ./keys:/keys
    env_file:
      - ./app.env
    depends_on:
      - db
    expose:
      - 8000
    restart: unless-stopped
    networks:
      - django_admin_school_net

  db:
    image: postgres
    env_file:
      - ./postgres_db.env
    ports:
      - "31700:5432"
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - django_admin_school_net

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./pgadmin.env
    ports:
      - "31750:80"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - django_admin_school_net

networks:
  django_admin_school_net:
    name: django_admin_school_net
    ipam:
      driver: default
      config:
        - subnet: "192.168.11.0/24"