# docker-compose run web python manage.py makemigrations
# docker-compose run web python manage.py migrate
# docker-compose run web python manage.py createsuperuser

version: '3'

services:
  
  db:
    image: postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=pgdb
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=password
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: ProyectoWeb
    volumes:
      - ./ProyectoWeb/media:/app/media
      - ./ProyectoWeb/static:/app/static
      - ./ProyectoWeb/logs:/var/log/app
    environment:
      - DATABASE_URL=postgres://pguser:password@db:5432/pgdb
    expose:
      - 8000
    links:
      - db:db
    depends_on:
      - db
    restart: unless-stopped
    
  nginx:
    build: nginx
    ports: 
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./ProyectoWeb/static:/app/static
      - ./ProyectoWeb/media:/app/media
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - web
    restart: unless-stopped